name = "sub-worker"
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "c3a7ca0f148f4359b44d50c228f9dae9"					#KV据库id
